apiVersion: v1
kind: Namespace
metadata:
  name: webapi-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  namespace: webapi-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: "#{repositoryUrl}#"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: webapi-namespace
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
