apiVersion: v1
kind: Namespace
metadata:
  name: "#{appName}#"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "#{appName}#"
  namespace: "#{appName}#"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "#{appName}#"
  template:
    metadata:
      labels:
        app: "#{appName}#"
    spec:
      containers:
      - name: "#{appName}#"
        image: "#{repositoryUrl}#"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "#{appName}#"
  namespace: "#{appName}#"
spec:
  selector:
    app: "#{appName}#"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
